chore: add  InterSCSimulator model to Sim-Diasca

diff --git a/traces/GNUmakefile b/traces/GNUmakefile
--- a/traces/GNUmakefile
+++ b/traces/GNUmakefile
@@ -1,32 +1,41 @@
 TRACES_TOP = .
 
 
-.PHONY: help help-traces                                               \
-		all register-version-in-header register-traces list-beam-dirs  \
-		add-prerequisite-plts link-plt                                 \
-		stats                                                          \
-		info-context info-versions info-traces info-compile            \
-		info-conditionals info-deps
+.PHONY: help help-intro help-traces                                   \
+		all register-version-in-header register-traces list-beam-dirs \
+		add-prerequisite-plts link-plt                                \
+		info-traces
 
 
-MODULES_DIRS = src doc conf test examples
-
+MODULES_DIRS = src doc #conf
 
 # To override the 'all' default target with a parallel version:
 BASE_MAKEFILE = true
 
 
+# No trace supervisor or graphical output wanted when running all tests from a
+# root directory (batch mode vs interactive one):
+CMD_LINE_OPT = "--batch"
+
+
+
 # Default target:
 help: help-intro help-traces
+
+
+help-intro:
+	@echo " Following main make targets are available for package $(PACKAGE_NAME):"
+
 
 help-traces:
 	@cd $(WOOPER_TOP) && $(MAKE) -s help-wooper
 
 
+
 register-version-in-header:
-	@if [ -z "$(VERSION_FILE)" ]; then \
-	echo "  Error, no version file defined." 1>&2; exit 52; else \
-	$(MAKE) -s register-traces; fi
+	@if [ -z "$(VERSION_FILE)" ] ; then \
+	echo "Error, no version file defined." 1>&2 ; exit 52 ; else \
+	$(MAKE) register-traces ; fi
 
 
 register-traces:
@@ -35,7 +44,7 @@ register-traces:
 
 # Useful to extract internal layout for re-use in upper layers:
 list-beam-dirs:
-	@for d in $(TRACES_BEAM_DIRS); do echo $$(readlink -f $$d); done
+	@for d in $(TRACES_BEAM_DIRS) ; do echo $$(readlink -f $$d) ; done
 
 
 add-prerequisite-plts: link-plt
@@ -43,38 +52,11 @@ add-prerequisite-plts: link-plt
 
 # As upper layers may rely on the 'traces' naming:
 link-plt:
-	@if [ ! "$(PLT_FILE)" = "$(TRACES_PLT_FILE)" ]; then /bin/ln -s --force $(PLT_FILE) $(TRACES_PLT_FILE); fi
-
-
-stats:
-	@$(MAKE_CODE_STATS) $(TRACES_TOP)
-
-
-# Typically useful to know the software context for continuous integration:
-info-context: info-platform info-versions
-
-
-info-versions:
-	@echo "MYRIAD_VERSION = $(MYRIAD_VERSION)"
-	@echo "WOOPER_VERSION = $(WOOPER_VERSION)"
-	@echo "TRACES_VERSION = $(TRACES_VERSION)"
+	@/bin/ln -s $(PLT_FILE) $(TRACES_PLT_FILE)
 
 
 info-traces:
 	@echo "ENABLE_TRACE_OPT = $(ENABLE_TRACE_OPT)"
-
-
-info-compile: info-compile-wooper
-
-
-info-conditionals:
-	@echo "TRACES_DEBUG_FLAGS = $(TRACES_DEBUG_FLAGS)"
-	@echo "TRACES_CHECK_FLAGS = $(TRACES_CHECK_FLAGS)"
-
-
-info-deps:
-	@echo "MYRIAD_TOP = $(MYRIAD_TOP) (i.e. $$(realpath $(MYRIAD_TOP)))"
-	@echo "WOOPER_TOP = $(WOOPER_TOP) (i.e. $$(realpath $(WOOPER_TOP)))"
 
 
 include $(TRACES_TOP)/GNUmakesettings.inc
diff --git a/wooper/GNUmakefile b/wooper/GNUmakefile
--- a/wooper/GNUmakefile
+++ b/wooper/GNUmakefile
@@ -1,16 +1,14 @@
 WOOPER_TOP = .
 
 
-.PHONY: help help-wooper                                                   \
-		all register-version-in-header register-wooper list-beam-dirs      \
-		add-prerequisite-plts link-plt                                     \
-		release release-zip release-bz2 release-xz                         \
-		prepare-release clean-release clean-archive stats                  \
-		info-context info-versions                                         \
-		info-compile info-conditionals info-deps
+.PHONY: help help-intro help-wooper                                   \
+		all register-version-in-header register-wooper list-beam-dirs \
+		add-prerequisite-plts link-plt                                \
+		send-release release release-zip release-bz2 release-xz       \
+		prepare-release clean-release clean-archive
 
 
-MODULES_DIRS = src doc conf test priv
+MODULES_DIRS = src doc examples
 
 
 # To override the 'all' default target with a parallel version:
@@ -22,18 +20,26 @@ WOOPER_RELEASES = $(WOOPER_RELEASE_ARCHIVE_BZ2) \
 				  $(WOOPER_RELEASE_ARCHIVE_XZ)
 
 
+SF_USER = wondersye
+
 
 # First target for default:
 help: help-intro help-wooper
 
+
+help-intro:
+	@echo " Following main make targets are available for package $(PACKAGE_NAME):"
+
+
 help-wooper:
-	@cd $(MYRIAD_TOP) && $(MAKE) -s help-myriad
+	@cd $(COMMON_TOP) && $(MAKE) -s help-common
+
 
 
 register-version-in-header:
-	@if [ -z "$(VERSION_FILE)" ]; then \
-	echo "Error, no version file defined." 1>&2; exit 51; else \
-	$(MAKE) -s register-wooper; fi
+	@if [ -z "$(VERSION_FILE)" ] ; then \
+	echo "Error, no version file defined." 1>&2 ; exit 51 ; else \
+	$(MAKE) register-wooper ; fi
 
 
 register-wooper:
@@ -42,7 +48,7 @@ register-wooper:
 
 # Useful to extract internal layout for re-use in upper layers:
 list-beam-dirs:
-	@for d in $(WOOPER_BEAM_DIRS); do echo $$(readlink -f $$d); done
+	@for d in $(WOOPER_BEAM_DIRS) ; do echo $$(readlink -f $$d) ; done
 
 
 add-prerequisite-plts: link-plt
@@ -50,12 +56,17 @@ add-prerequisite-plts: link-plt
 
 # As upper layers may rely on the 'wooper' naming:
 link-plt:
-	@if [ ! "$(PLT_FILE)" = "$(WOOPER_PLT_FILE)" ]; then /bin/ln -s --force $(PLT_FILE) $(WOOPER_PLT_FILE); fi
+	@/bin/ln -s $(PLT_FILE) $(WOOPER_PLT_FILE)
 
 
 # Note: the source archives are not produced in this directory, but in its
 # parent, so that everything related to WOOPER (including these rules) remains
 # self-contained.
+
+send-release: release
+	@echo "     Sending WOOPER releases $(WOOPER_RELEASES) to Sourceforge"
+	@cd .. && rsync -avP -e ssh $(WOOPER_RELEASES) \
+	$(SF_USER)@frs.sourceforge.net:uploads/
 
 
 release: release-zip release-bz2 release-xz
@@ -65,28 +76,28 @@ release: release-zip release-bz2 release-xz
 release-zip: prepare-release
 	@echo "     Creating WOOPER release archive $(WOOPER_RELEASE_ARCHIVE_ZIP)"
 	@cd .. && zip -r $(WOOPER_RELEASE_ARCHIVE_ZIP) $(WOOPER_RELEASE_BASE) \
-	&& echo "     Archive $(WOOPER_RELEASE_ARCHIVE_ZIP) ready in $$(pwd)"
+	&& echo "     Archive $(WOOPER_RELEASE_ARCHIVE_ZIP) ready in "`pwd`
 
 
 release-bz2: prepare-release
 	@echo "     Creating WOOPER release archive $(WOOPER_RELEASE_ARCHIVE_BZ2)"
 	@cd .. && tar chvjf $(WOOPER_RELEASE_ARCHIVE_BZ2) $(WOOPER_RELEASE_BASE) \
-	&& echo "     Archive $(WOOPER_RELEASE_ARCHIVE_BZ2) ready in $$(pwd)"
+	&& echo "     Archive $(WOOPER_RELEASE_ARCHIVE_BZ2) ready in "`pwd`
 
 
 release-xz: prepare-release
 	@echo "     Creating WOOPER release archive $(WOOPER_RELEASE_ARCHIVE_XZ)"
 	@cd .. && tar chvjf $(WOOPER_RELEASE_ARCHIVE_XZ) $(WOOPER_RELEASE_BASE) \
-	&& echo "     Archive $(WOOPER_RELEASE_ARCHIVE_XZ) ready in $$(pwd)"
+	&& echo "     Archive $(WOOPER_RELEASE_ARCHIVE_XZ) ready in "`pwd`
 
 
 # The '-L' option with cp is used so that symbolic links are replaced by their
 # actual target file, otherwise tar would include dead links in releases.
-#
 prepare-release: clean clean-release
 	@echo "     Preparing release archive for WOOPER $(WOOPER_VERSION)"
-	@cd .. && mkdir -p $(WOOPER_RELEASE_BASE) && /bin/cp -L -r myriad wooper $(WOOPER_RELEASE_BASE)
+	@cd .. && mkdir -p $(WOOPER_RELEASE_BASE) && /bin/cp -L -r common wooper $(WOOPER_RELEASE_BASE)
 	@cd ../$(WOOPER_RELEASE_BASE) && mv wooper/top-GNUmakefile-for-releases GNUmakefile
+	-@cd .. && find $(WOOPER_RELEASE_BASE) -type d -a -name '.svn' -exec /bin/rm -rf '{}' ';' 2>/dev/null
 	-@cd .. && find $(WOOPER_RELEASE_BASE) -type d -a -name '.git' -exec /bin/rm -rf '{}' ';' 2>/dev/null
 	-@cd .. && find $(WOOPER_RELEASE_BASE) -type f -a -name '*.beam' -exec /bin/rm -f '{}' ';' 2>/dev/null
 
@@ -95,37 +106,12 @@ clean: clean-release clean-archive
 
 
 clean-release:
-	@echo "   Cleaning release archive for WOOPER"
+	@echo "     Cleaning release archive for WOOPER"
 	-@cd .. && /bin/rm -rf $(WOOPER_RELEASE_BASE)
 
 
 clean-archive:
 	-@cd .. && /bin/rm -f $(WOOPER_RELEASES)
-
-
-stats:
-	@$(MAKE_CODE_STATS) $(WOOPER_TOP)
-
-
-# Typically useful to know the software context for continuous integration:
-info-context: info-platform info-versions info-source-layout
-
-
-info-versions:
-	@echo "MYRIAD_VERSION = $(MYRIAD_VERSION)"
-	@echo "WOOPER_VERSION = $(WOOPER_VERSION)"
-
-
-info-compile: info-compile-wooper
-
-
-info-conditionals:
-	@echo "WOOPER_DEBUG_FLAGS = $(WOOPER_DEBUG_FLAGS)"
-	@echo "WOOPER_CHECK_FLAGS = $(WOOPER_CHECK_FLAGS)"
-
-
-info-deps:
-	@echo "MYRIAD_TOP = $(MYRIAD_TOP) (i.e. $$(realpath $(MYRIAD_TOP)))"
 
 
 include $(WOOPER_TOP)/GNUmakesettings.inc
